# Generated by Django 4.2.1 on 2023-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='code_snippet',
            field=models.TextField(blank=True, max_length=20000000),
        ),
    ]
